# Generated by Django 3.1.5 on 2021-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='resenha',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.TextField(max_length=100),
        ),
    ]
